### ISSUE TITLE
Nachfrage: Für Unterstützung

### ISSUE THREAD

**Issue by FundyJo** [Commandcracker/gucken#10]
Hallo Commandcracker...

habe mir dein Projekt angeschaut finde es sehr gut und würde dich gerne unterstützen falls du noch hilfe brauchst für andere Streaming möglichkeiten ich selbst Arbeite aktuell viel mit React, Python, Ruby, C++, C, C#.

Falls ja melde dich gerne bei mir entweder per Antwort hier oder auf Discord: fundyjo

**Comment by Commandcracker** [comment]
Momentan ist der Plan, alle Features fertigzustellen und bestehende Features zu verbessern. Die Features die grade im Fokus Ligen sind "Discord Presence", "Remember watch time" und "Tracker support".

Plan ist natürlich auch eine große Menge an Streaming Seiten zu unterstützen. Ich habe versucht, bs.to zu unterstützen, aber das Problem ist, das Google CAPTCHA. Man könnte selenium nutzen, das würde dann aber leider nicht auf Android funktionieren. Am besten wehre es, wenn man es hinkriegt den CAPTCHA headless zu lösen.

Wenn du Support für eine Seite hinzufügen möchtest, dann mach das :D
PRs sind immer willkommen!

**Comment by FundyJo** [comment]
Super Freut mich!

falls du discord hast füge mich mal hinzu falls ich lösungen finde würde ich sie dir schicken
