### ISSUE TITLE
how to customize it

### ISSUE THREAD

**Issue by DarkLite25** [Commandcracker/gucken#19]
hello i like this code and i want to customize it or modified to my liking
and i dont know how to do that

**Comment by Commandcracker** [comment]
1. You need to clone the repository `git clone https://github.com/Commandcracker/gucken.git`
2. cd into the cloned repository `cd gucken`
3. Run `pip install -e .` to install gucken in editable mode

and then you can make any changes to the code. Feel free to create a PR if you think that your changes should be merged with upstream!

**Warning: The code is currently very messy, as this project is in Pre-Alpha, this is why it might be hard to implement changes!**

Did this answer you'r question ?

**Comment by DarkLite25** [comment]
thank you , yeah it answer it i will take llok on the code and have fun with it until stable version release.
